[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
proxy_mode = True
admin_passwd = $pbkdf2-sha512$600000$vZeSEoJQypmTcm5tLYUwhg$gz4UxDo0nbFC7UDpiTlXS/sKwFSGuAG50IHHTeyLfSt31IVS1pK81DJEARhHnXh9fHoJZWTX1a3lC8yKedkSgw

